
create table {schema}.seed (
	id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	first_name VARCHAR2(50 CHAR),
	last_name VARCHAR2(50 CHAR),
	email VARCHAR2(50 CHAR),
	gender VARCHAR2(50 CHAR),
	ip_address VARCHAR2(20 CHAR)
);

create table {schema}.agg (
	last_name VARCHAR(50),
	count NUMBER
);



insert into {schema}.seed (first_name, last_name, email, gender, ip_address) values ('Jack', 'Hunter', 'jhunter0@pbs.org', 'Male', '59.80.20.168');
insert into {schema}.seed (first_name, last_name, email, gender, ip_address) values ('Kathryn', 'Walker', 'kwalker1@ezinearticles.com', 'Female', '194.121.179.35');
insert into {schema}.seed (first_name, last_name, email, gender, ip_address) values ('Gerald', 'Ryan', 'gryan2@com.com', 'Male', '11.3.212.243');


insert into {schema}.agg (last_name, count) values ('Hunter', 2);
insert into {schema}.agg (last_name, count) values ('Walker', 2);
insert into {schema}.agg (last_name, count) values ('Ryan', 2);
